# Generated by Django 5.0.1 on 2024-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(max_length=255, upload_to='blogs/images/'),
        ),
    ]
