# Generated by Django 5.0.1 on 2024-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='blogs/images/'),
        ),
    ]
