# Generated by Django 5.0.1 on 2024-01-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured',
        ),
    ]
